# basic options
title: about
author: @mochekwa
email: sharingsite@mail
description: Community sharing site for ways to learn Earn, Play Earn,Crypto updated and Airdrops
twitter_username: @sharingsite
github_username: @mochekwa

# build settings
markdow: kramdown
theme: hacker
